### ISSUE TITLE
感谢

### ISSUE THREAD

**Issue by liuran001** [autersu/Lenovo_G400_EFI#1]
感谢大佬，考虑做10.15的efi吗

**Comment by autersu** [comment]
已经换MBP了,电脑卖掉了,所以应该做不了了.
但是之前试着装过10.15,与这个EFI不同的地方是: 第一,在启动时,屏蔽掉镜像里自带的那个触摸板/键盘驱动(好像是ps2XXX什么的).,使用usb键盘驱动(usbinterjectall那个),不然启动不了; 第二,要屏蔽几个自带补丁,但忘是哪个了(不过在做完第一项启动依然黑屏之后,把黑屏最后一行错误代码往百度上搜下,上面应该有说明),安装完成后,用那个四叶草配置工具把那个相对应的改动下就行了,不然卡黑屏.
不过据说10.15的后续版本苹果官方会屏蔽这种第三方驱动,所以10.15后续的升级可能会有麻烦.

**Comment by liuran001** [comment]
> 已经换MBP了,电脑卖掉了,所以应该做不了了.
> 但是之前试着装过10.15,与这个EFI不同的地方是: 第一,在启动时,屏蔽掉镜像里自带的那个触摸板/键盘驱动(好像是ps2XXX什么的).,使用usb键盘驱动(usbinterjectall那个),不然启动不了; 第二,要屏蔽几个自带补丁,但忘是哪个了(不过在做完第一项启动依然黑屏之后,把黑屏最后一行错误代码往百度上搜下,上面应该有说明),安装完成后,用那个四叶草配置工具把那个相对应的改动下就行了,不然卡黑屏.
> 不过据说10.15的后续版本苹果官方会屏蔽这种第三方驱动,所以10.15后续的升级可能会有麻烦.

好的，谢谢了
